#ifndef _MASK_MANAGER_H_
#define _MASK_MANAGER_H_

//#define IDENTITY_KID_MASK	0x80
#define MOVEMENT_KID_UPXX_MASK	0x01
#define MOVEMENT_KID_DOWN_MASK	0x02
#define MOVEMENT_KID_LEFT_MASK	0x04
#define MOVEMENT_KID_RGHT_MASK	0x08

#define MOVEMENT_PRO_UPXX_MASK	0x10
#define MOVEMENT_PRO_DOWN_MASK	0x20
#define MOVEMENT_PRO_LEFT_MASK	0x40
#define MOVEMENT_PRO_RGHT_MASK	0x80

#define MOVEMENT_ADI_UPXX_MASK	0x01
#define MOVEMENT_ADI_DOWN_MASK	0x02
#define MOVEMENT_ADI_LEFT_MASK	0x04
#define MOVEMENT_ADI_RGHT_MASK	0x08

#define MOVEMENT_SUZ_UPXX_MASK	0x10
#define MOVEMENT_SUZ_DOWN_MASK	0x20
#define MOVEMENT_SUZ_LEFT_MASK	0x40
#define MOVEMENT_SUZ_RGHT_MASK	0x80

//#define VELOCITY_KID_NORM_MASK	0x00
#define VELOCITY_KID_SLOW_MASK	0x01
#define VELOCITY_KID_FAST_MASK	0x02
#define VELOCITY_PRO_SLOW_MASK	0x04
#define VELOCITY_PRO_FAST_MASK	0x08
#define VELOCITY_ADI_SLOW_MASK	0x10
#define VELOCITY_ADI_FAST_MASK	0x20
#define VELOCITY_SUZ_SLOW_MASK	0x40
#define VELOCITY_SUZ_FAST_MASK	0x80

#endif//_MASK_MANAGER_H_